### ISSUE TITLE
Doesn't build with iojs

### ISSUE THREAD

**Issue by gtarcea** [capriza/node-busmq#1]
The package.json has a dependency on hiredis 0.1.17, which is incompatible with the version of V8 used in iojs. The hiredis verion 0.2.0 builds fine. As a work around I can build with node then switch back to iojs, but its not an ideal solution.

**Comment by fujifish** [comment]
Thanks!.
Fixed in version 0.8.8.

**Comment by gtarcea** [comment]
Just tested it and it works. Wow, thanks for the fast response!
