### ISSUE TITLE
Pub/Sub model

### ISSUE THREAD

**Issue by ronnen** [capriza/node-busmq#11]
Hey Nadav,

Is it possible to add a pub/sub mechanism to the bus so that clients can listen on specific events flowing through the bus? I have a great use case for it.

Thanks,

R

**Comment by fujifish** [comment]
There's already a persistent pub/sub ability but if I understand correctly you're talking about true pub/sub.
I'll add this option in the near future.

**Comment by fujifish** [comment]
Released version 0.12.0 with new pubsub capabilities.
```javascript
var subscriber = bus.pubsub('my pubsub channel');
subscriber.on('message', function(message) {
  // do whatever
});
subscriber.subscribe();

var publisher = bus.pubsub('my pubsub channel');
publisher.publish('this is a message');
```

**Comment by ronnen** [comment]
That's great new Nadav!
Thanks!

Sent from my iPhone

On Aug 8, 2015, at 12:34 PM, Nadav Fischer <notifications@github.com> wrote:

Released version 0.12.0 with new pubsub capabilities.

var subscriber = bus.pubsub('my pubsub channel');
subscriber.on('message', function(message) {
  // do whatever
});
subscriber.subscribe();
var publisher = bus.pubsub('my pubsub channel');
publisher.publish('this is a message');

—
Reply to this email directly or view it on GitHub
<https://github.com/capriza/node-busmq/issues/11#issuecomment-128944125>.

**Comment by Kamil93** [comment]
Is it possible to publish and subscribe on same variable?

var pubsub = bus.pubsub('all-workers');
pubsub.on('message', function(message) {
  // do whatever
});
pubsub.subscribe();

pubsub.publish('rebellion!!!');

**Comment by fujifish** [comment]
Absolutely!
