### ISSUE TITLE
Lack of error first callbacks was a surprise

### ISSUE THREAD

**Issue by ChiperSoft** [capriza/node-busmq#14]
Forgive me if this is documented in the readme and I just failed to see it, but I expected all the callbacks on queue functions to be error first, as is the tradition in node development.

That'd be a pretty big breaking change to fix, but perhaps you could make it clearer in the readme?  Ideally that should probably happen tho, as currently there doesn't appear to be any way to tell which action triggered an error.

**Comment by fujifish** [comment]
Is the problem that an error isn't firing at all or that errors are fired as events instead of being provided in context of the action?

**Comment by fujifish** [comment]
I gave your suggestion some thought and decided to make the proposed change.
Since this is a breaking change I had to bump the major version, so I've released version 1.0.0 with the suggested callback fixes.
Thanks for this important suggestion!

**Comment by ChiperSoft** [comment]
Wow, amazing response to this and the other issues I opened.  You've written a great library here, keep up the good work.
