### ISSUE TITLE
Fails to install on windows using node V4.2.4 and npm v3.2.1

### ISSUE THREAD

**Issue by kpturner** [capriza/node-busmq#20]
Fails installing hiredis so not sure if I should report it there or here:

<pre>
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\kturner\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.2.1
gyp info using node@4.2.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:78:19)
gyp verb `which` failed     at E (C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:82:29)
gyp verb `which` failed     at C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:93:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at F (C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:78:19)
gyp verb `which` failed     at E (C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:82:29)
gyp verb `which` failed     at C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:93:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python [Error: not found: python]
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kturner\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kturner\repos\rns-node\node_modules\hiredis
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm verb lifecycle hiredis@0.4.1~install: unsafe-perm in lifecycle true
npm verb lifecycle hiredis@0.4.1~install: PATH: C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\kturner\repos\rns-node\node_modules\hiredis\node_modules\.bin;C:\Users\kturner\repos\rns-node\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Live\Shared;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\IBM\Client Access\Emulator;C:\Program Files (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client Access\;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\010 Editor;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Users\kturner\AppData\Local\Pandoc\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\kturner\AppData\Roaming\npm
npm verb lifecycle hiredis@0.4.1~install: CWD: C:\Users\kturner\repos\rns-node\node_modules\hiredis
npm info lifecycle hiredis@0.4.1~install: Failed to exec install script
npm verb unlock done using C:\Users\kturner\AppData\Roaming\npm-cache\_locks\staging-b3da145b0915bc0d.lock for C:\Users\kturner\repos\rns-node\node_modules\.staging
rns-node@0.0.0 C:\Users\kturner\repos\rns-node
└── (empty)

npm verb stack Error: hiredis@0.4.1 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\kturner\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid hiredis@0.4.1
npm verb cwd C:\Users\kturner\repos\rns-node
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kturner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "busmq" "--save" "--verbose"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hiredis
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kturner\repos\rns-node\npm-debug.log
npm ERR! code 1
</pre>

**Comment by kpturner** [comment]
I think I am stuck.  I can install Python 2 but then it fails to build hiredis due to a dependency on c++11 :(

**Comment by fujifish** [comment]
Can you try cloning hiredis repo and building it? If it fails then open an issue there.
Which version of python 2 are you using?

Alternatively, you can clone node-busmq, remove hiredis from the deps in package.json and rebuild.
It should work without hiredis as well.

**Comment by kpturner** [comment]
I prefer your second option and I am happy to try it.   Will there be any negative impact on your solution without hiredis?

By the way, I installed Python 2.7.11

**Comment by fujifish** [comment]
Shouldn't be anything too significant. hiredis is used for improved parsing for the protocol transfer, so it depends on how much data you're planning on transferring.
If you can update when you get it working without hiredis, I'll close the issue.

**Comment by kpturner** [comment]
When you say "rebuild it" what do you mean exactly?

I have cloned the git repo into node_modules/busmq, renamed the .git folder, removed the hiredis dependency and then run npm install (successfully).  Is that it?

**Comment by fujifish** [comment]
yep, that should do it.

**Comment by kpturner** [comment]
OK - it works fine.

I have a question - although perhaps not relevant to this log.
Is it possible to enqueue messages with a key, such that a consumer can only pick up messages with that key?

The scenario is that a client can send a message.  Any number of several consumers might pick up the message.  The response must only be available to the original client.   Possible?

**Comment by fujifish** [comment]
This is currently not a built-in feature.
However, a simple solution would be that every client creates a unique "response" queue that only he will be consuming from. The message the client sends will contain the response queue name, and the responder will simply push the response to the correct queue. 
Makes sense?

**Comment by kpturner** [comment]
Yes this was exactly my intention. My only concern was whether or not queue creation was an expensive process, as it will be happening hundreds of times a minute across the system. As an aside, due queues expire after a period of inactivity, or after a restart?

**Comment by fujifish** [comment]
1. creating queues _is_ more expensive than just using them. I haven't performed any benchmarking through, so I suggest you test it out.
2. queues expire after a defined the TTL passes without any clients attached to the queue. As long as there is at least one client attached, the queue will not expire. Restart does not expire the queues.
