### ISSUE TITLE
Add Redis sentinels and Redis cluster support

### ISSUE THREAD

**Issue by bgrieder** [capriza/node-busmq#24]
Now that we have Ioredis support (https://github.com/capriza/node-busmq/pull/23) , add support for a Redis sentinels layout and a Redis cluster layout.

I have started work on this 

 - re-using the idea of 'driver' that I have externalised to its own module 
     - to make it more flexible in supporting all 4 cases (direct node-redis, direct ioredis, sentinels (ioredis), cluster(ioredis))
     - to remove driver specific code as much as possible from `bus.js`, `queue.js` and `connection.js` 
     - to provide driver specific optimisations and normalzations
 - externalising test functions in their own module since most can be re-used to test all 4 cases

I will make multiple commits on my fork. Let me know when you are interested in "intermediate" PRs on these commits.

**Comment by fujifish** [comment]
Excellent. I'll try to take a look at your fork before you open a PR if that's ok.

**Comment by bgrieder** [comment]
@fujifish Sentinels support now looks OK and I have started Cluster support.
I will provide better documentation but in the meantime can you please look (in my fork) at

- `sentinels.mocha.js` for Bus creation options and tests for a Redis Sentinels Layout
- `cluster.mocha.js` for Bus creation options and tests for a Redis Cluster Layout

Scripts are provided to start/stop a sentinels layout and a cluster layout in respectively, `helpers/redis-sentinels.js` and `helpers/redis-cluster.js`

One issue I need your help with is that there are some restrictions on using `multi` in a Cluster Layout (at least with Redis 3.0.5). If you run the tests on the cluster, you will see it happening:

    ./node_modules/.bin/mocha test/cluster.mocha.js 
    .....
    Error: All keys in the pipeline should belong to the same slot(expect "bus:queue:test0.7103818657342345:msgid" belongs to slot 11260).

You mentioned rewriting `Queue#push()` so that everything goes into the Lua script. Maybe this is a good time and will fix that issue ?

Cheers

**Comment by fujifish** [comment]
Looks like you've done some major work so it might take me some time to review it all. 
I'll start working on the push lua script as soon as I can.

**Comment by bgrieder** [comment]
@fujifish Take your time. I don't plan to do much more until you have reviewed it, except maybe merge the few commits you made since I forked.

**Comment by fujifish** [comment]
I've updated the queue push method to use a revised lua script so `multi` command is no longer used.
Give cluster another shot.

**Comment by bgrieder** [comment]
@fujifish Thanks I have merged your changes into my fork.

Cluster is still not working, but we are progressing.
The error return by the call to the Lua script is now: `CROSSSLOT Keys in request don't hash to the same slot`

As explained in this [doc](http://redis.io/topics/cluster-spec#keys-hash-tags)

 - all keys in a same operation must belong to the same hash slot
 - the calculation of the hash slot for a key may be influenced by the use of curly brackets in the key name

The keys which are sent to the `push` Lua script, typically look like this

    KEY1 bus:queue:test0.6087149165105075:metadata
    KEY2 bus:queue:test0.6087149165105075:messages
    KEY3 bus:queue:test0.6087149165105075:msgid
    KEY4 bus:queue:test0.6087149165105075:toack

If my understanding is correct using this instead would solve the issue:

    KEY1 {bus:queue:test0.6087149165105075}:metadata
    KEY2 {bus:queue:test0.6087149165105075}:messages
    KEY3 {bus:queue:test0.6087149165105075}:msgid
    KEY4 {bus:queue:test0.6087149165105075}:toack

Do you feel this is doable ?

**Comment by bgrieder** [comment]
Actually, adding something like this in the `Queue` constructor:

      this.id = this.bus.options.layout === 'cluster' ? "{bus:queue:" + name + "}" : "bus:queue:" + name;

seems to mostly fix it (there are other issues).
I added the `layout` test in order to not disrupt existing implementations. 
wdyt ?

**Comment by fujifish** [comment]
I agree, exiting deployments cannot be hurt. Your fix makes sense and looks pretty simple.
What are the other issues?

**Comment by bgrieder** [comment]
There is a problem regrading the way the cluster caches Lua scripts: the scripts are not always available when `evalsha` is called. I do not know at this stage whether this is an ioredis or a redis cluster issue, but redis 3.0.7 looks like a good culprit.

To illustrate the issue I have committed some code on the HEAD of my fork.

I have basically added a method in `Bus` that waits for scripts to be loaded

    Bus.prototype._waitForScripts = function(connection, done) {
      var _this = this;
      var hashes = Object.keys(this.scripts).map(function(key){ return _this.scripts[key].hash;});
      connection.script('exists', hashes, function(err, res) {
  
        if (res.length !== hashes.length || res.filter(function(r) { return r === 0 }).length === 0) {
          done();
        } else {
          console.log('XXXXXXXSCRIPTS NOT ALL THERE: ', res);
          setTimeout(function() {_this._waitForScripts(connection, done);}, 500);
        }
      });
    };


This method is called on the callback of `connection.script('load',...` in  `Bus.protoype.online` 

            if (_this.options.layout === 'cluster') {
              //unfortunately in a cluster, scripts tend to take a bit to be actually loaded
              _this._waitForScripts(connection, function() {
                _this.emit('online');
              });
            }
            else {
              _this.emit('online');
            }

When the 4 scripts are loaded the response to `connection.scripts('exist',...)` should be an array `[1,1,1,1]`. The `waitForScripts` method calls `exist` until it gets that pattern.

Unfortunately, it almost never gets it and actually gets results that do not make any sense:

    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ] 
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 1, 1, 0, 1 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 1, 1, 0, 1 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 1, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 1, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 1, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 1, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 1, 1, 0, 1 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 1, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
    XXXXXXXSCRIPTS NOT ALL THERE:  [ 0, 0, 0, 0 ]
   ....

Ideas more than welcome....

**Comment by fujifish** [comment]
From what I read I believe the script load command should be sent to **all** nodes. 
ioredis supports this by using the `cluster.to('all').call('script')` method, so I was thinking it can be done in the `Connection.prototype._connect` method and give special handling for the `script load` command

Want to give it a try?

**Comment by bgrieder** [comment]
That was it ! Scripts must (forcibly) be loaded on all masters... The fix is committed in my branch

Basically, I had to add : 
 
- in `Connection#_connect()`


        if (this.layout === 'cluster') {
          this['to'] = function() {
            return _this.clients[type]['to'].apply(client, arguments);
          }
        }


- in `Bus#_online()`

        if (_this.options.layout === 'cluster') {
          connection.to( 'masters' ).call( 'script', 'load', script.content, handler );
        } else {
          connection.script( 'load', script.content, handler );
        }

**Comment by bgrieder** [comment]
Almost there on Cluster. 
Pub/Sub generally works (subscribers receive messages) however two tests are failing

- 'should receive subscribe/unsubscribe and message events'

    s.on('subscribed', function() {
      // create publisher
      var p = bus.pubsub(qName);
      p.on('error', done);
      p.publish('hello', function(err, count) {
        Should(err).be.exactly(null);
        count.should.be.exactly(1);        <<------ count is zero (but 'hello' is received by subscriber')
      });
      p.publish('world', function(err, count) {
        Should(err).be.exactly(null);
        count.should.be.exactly(1);        <<------ count is zero (but 'world' is received by subscriber')
        if (_count() === 3) {
          s.unsubscribe();
        }
      });
    });
    s.subscribe();
  });

 - and the equivalent test for the same reason on federation tests

I have not researched the issue

**Comment by fujifish** [comment]
have you made any progress?

**Comment by bgrieder** [comment]
I have had no time to look at it in the past few days. 
To understand what is going on I need to deep dive in your pub/sub code.
Count aside, pub/sub is generally working with a redis cluster.

**Comment by fujifish** [comment]
OK thanks, I'll give it a shot to see if I find anything

-- nadav

**Comment by fujifish** [comment]
I've dome some searching and I think it's probably because the returned number of subscribers that received the message only includes subscribers from the same node that performed the publish. assuming that the subscriber resides on a different node than the one that publishes, the result would be 0.
I haven't confirmed this or performed any testing, but if you can try to set up a cluster with just a single node and run the test, I'm pretty sure the result would be 1.

**Comment by bgrieder** [comment]
> you can try to set up a cluster with just a single node and run the test, I'm pretty sure the result would be 1.

Unfortunately I cannot run this test: the minimal number of master nodes in a cluster is 3.
I do not think I cannot go further than disabling this test and I consider the code to be complete.

**Comment by bgrieder** [comment]
btw the tests sometimes pass which validate your theory

**Comment by fujifish** [comment]
I agree. Disable this specific test, and I'll add a note to the readme that receiving the number of subscribers after a publish is not supported in cluster mode.
Make the pull request when you're ready

**Comment by fujifish** [comment]
Rather than disabling the test, just disable the check for the number of subscribers if in cluster mode

**Comment by bgrieder** [comment]
> Rather than disabling the test, just disable the check for the number of subscribers if in cluster mode
Yes that is what I meant to do

**Comment by bgrieder** [comment]
https://github.com/capriza/node-busmq/pull/27
