### ISSUE TITLE
MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk.

### ISSUE THREAD

**Issue by kpturner** [capriza/node-busmq#25]
Not necessarily an issue with busmq itself, but I am looking for some pointers.  If I leave two processes communicating with each other with busmq for a long period of time (say 15 hours) then it eventually starts throwing this error.  The messages are enqueued once every 5 seconds, so nothing too strenuous.  It points to some sort of memory leak.   Anyone else experiencing this?

**Comment by kpturner** [comment]
I can mask the error in the config with "config set stop-writes-on-bgsave-error no" but this apparently is not a fix, it just stops the error.  I will still have info that occasionally will not be written to disk.

**Comment by fujifish** [comment]
Can you provide some code that reproduces this?

**Comment by kpturner** [comment]
Not easily I am afraid.  It is happening in the bowels of a large(ish) application and it is difficult to find the time to pull out the relevant bits and replicate.  I do have a stack trace though:
`uncaughtException: Uncaught, unspecified "error" event. (error setting key bus:queue:out_default_rnsdta:metadata expiration to 30: Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.)
Error: Uncaught, unspecified "error" event. (error setting key bus:queue:out_default_rnsdta:metadata expiration to 30: Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.) at Queue.emit (events.js:144:17) at C:\Users\kturner\repos\rns-node\node_modules\busmq\lib\queue.js:136:15 at Command.commands.forEach._this.(anonymous function).arguments.(anonymous function) [as callback] (C:\Users\kturner\repos\rns-node\node_modules\busmq\lib\connection.js:206:18) at RedisClient.return_error (C:\Users\kturner\repos\rns-node\node_modules\redis\index.js:571:25) at HiredisReplyParser. (C:\Users\kturner\repos\rns-node\node_modules\redis\index.js:315:18) at emitOne (events.js:77:13) at HiredisReplyParser.emit (events.js:169:7) at HiredisReplyParser.execute (C:\Users\kturner\repos\rns-node\node_modules\redis\lib\parser\hiredis.js:41:18) at RedisClient.on_data (C:\Users\kturner\repos\rns-node\node_modules\redis\index.js:547:27) at Socket. (C:\Users\kturner\repos\rns-node\node_modules\redis\index.js:102:14) at emitOne (events.js:77:13) at Socket.emit (events.js:169:7) at readableAddChunk (_stream_readable.js:146:16) at Socket.Readable.push (_stream_readable.js:110:10) at TCP.onread (net.js:523:20)
`

**Comment by fujifish** [comment]
Can you check if there are any keys in your redis that do not have an expiration set for them?
Also, there might be some queue that grows indefinitely. You can check large keys running `redis-cli --bigkeys`

**Comment by kpturner** [comment]
This should replicate it

[busmq#25.zip](https://github.com/capriza/node-busmq/files/178003/busmq.25.zip)

**Comment by kpturner** [comment]
Nothing seems to be unusual in redis.  Cannot find any keys with no expiration and --bigkeys shows
`# Press ctrl+c when you have had enough of it... :)
# You can use -i 0.1 to sleep 0.1 sec every 100 sampled keys
# in order to reduce server load (usually not needed).

Biggest string found so far 'bus:queue:out_default_rnsuat:msgid' with 2 bytes.
Biggest hash   found so far 'bus:queue:in_default_rnsdta_8756b165-b9e9-4e55-8120-fbeab698f113:metadata' with 1 fields.
Biggest string found so far 'bus:queue:myoutq:msgid' with 3 bytes.`

then it crashes!

**Comment by fujifish** [comment]
The exception specifies to check redis logs for the error. Are there more details there?

**Comment by kpturner** [comment]
> [3612] 17 Mar 13:42:19.593 # BeginForkOperation: system error caught. error code=0x000005af, message=BeginForkOperation: VirtualProtect failed for the heap: unknown error
> 
> [3612] 17 Mar 13:42:19.593 # Can't save in background: fork: Invalid argument
> [3612] 17 Mar 13:42:24.340 * 10000 changes in 60 seconds. Saving...
> [3612] 17 Mar 13:42:24.408 * Background saving started by pid 19164
> [19164] 17 Mar 13:42:28.996 # 
> 
> === REDIS BUG REPORT START: Cut & paste starting from here ===
> [19164] 17 Mar 13:42:28.996 # Redis version: 2.8.2400
> [19164] 17 Mar 13:42:28.996 # --- ABORT
> [19164] 17 Mar 13:42:28.996 # --- STACK TRACE
> redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x00000016, 0x40152A30, 0x00000000, 0x00000001)
> redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:207)(0x00000001, 0x4E93453D, 0x40135210, 0x09676437)
> redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0x00000000, 0x00000040, 0x00000030)
> redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0x40135210, 0x40038F12, 0x00000001, 0x0014F688)
> redis-server.exe!dlmalloc(c:\release\redis\src\win32_interop\win32_dlmalloc.c:4638)(0x00000030, 0x00000009, 0x00000003, 0x40135210)
> redis-server.exe!zmalloc(c:\release\redis\src\zmalloc.c:143)(0x0014F710, 0x00000009, 0x4013E9D8, 0x00000006)
> redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:681)(0x40135210, 0x02740000, 0x00000000, 0x03742754)
> redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:760)(0xFC640000, 0x56ED9062, 0x02740000, 0x00000168)
> redis-server.exe!QForkChildRun(c:\release\redis\src\win32_interop\win32_qfork.cpp:332)(0x00000006, 0xFFFFFFFF, 0x0033EA20, 0x00000000)
> redis-server.exe!QForkStartup(c:\release\redis\src\win32_interop\win32_qfork.cpp:740)(0xFFFFFFFF, 0x0033EA20, 0x00000006, 0x00000000)
> redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1333)(0x00000000, 0x00000000, 0x00000000, 0xFFFFE000)
> redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x400344CC, 0x00000000, 0x00000000)
> KERNEL32.DLL!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x07392D70, 0x00000000, 0x00000000, 0x00000000)
> ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
> ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
> [19164] 17 Mar 13:42:32.180 # 
> === REDIS BUG REPORT END. Make sure to include from START to END. ===
> 
>        Please report this bug by following the instructions at:
> 
>      http://github.com/MSOpenTech/redis/wiki/Submitting-an-Issue
> 
>     Suspect RAM error? Use redis-server --test-memory to verify it.
> 
> 
> [3612] 17 Mar 13:42:48.971 # fork operation failed

**Comment by kpturner** [comment]
Mmmmm, found this:  https://github.com/MSOpenTech/redis/issues/407

**Comment by fujifish** [comment]
This doesn't seem related to busmq so I'm closing.
