### ISSUE TITLE
Orphaned items 

### ISSUE THREAD

**Issue by kpturner** [capriza/node-busmq#26]
In issue #25 you asked me if I am seeing any redis records lingering in the database with no expiration.  The answer is yes.

I seem to get an occasional build up of queue records that I have created and then attach like this:
queue.attach({ttl:1});
queue.consume();

When a message arrives on the queue I detach from it.

In most cases these queues then vanish from the redis database automagically.  But on occasion I can see orphans just sitting there.  They never go away until I manually delete them,

The key contains:
row=1
ttl=1

The real TTL on the key (the one that redis takes care of) contains -1.

**Comment by kpturner** [comment]
Would this be a symptom of an abnormal termination?  It it normal for these entries to have a TTL of -1?

**Comment by fujifish** [comment]
Keys should never have a -1 expiration to ensure that there are no leaks even in an event of an abnormal termination. If there are lingering keys then it's a bug in busmq, unless there's a bug in redis...

Issue #21 was about fixing such a situation. Can you try to use the latest version of busmq to see if it's still reproducing, and if it does then provide code to reproduce?

**Comment by kpturner** [comment]
Issue #21  was mine too - so I do have that fix already.  This seems a bit different to issue 21.  With that it was consistently leaving the orphans but now it is quite a rare occurrence.   I will monitor for a while to see if I can spot a pattern.

**Comment by fujifish** [comment]
It'll help to know the full name if the leaked key and the code that was used to create/attach/detach from the queue. 
Also, please try to use the latest version since there was a change in how messages get pushed to a queue

**Comment by kpturner** [comment]
OK I will update it.    The code to repeat it is identical to the code that I sent for #21

The queue (key) takes the form:
bus:queue:in_default_rnsdta_<blah>

where blah is a uuid created with uuid.v4()

This is a technique where I pass a transactions to one of many child-processes, and wait for a response on a uniquely named queue that only lives for the duration of the transaction.  So when I pass the transaction to the child-process, part of the payload contains the name of the unique queue I want the response on.  Once the response is received both the client and child-process disconnect and the queue expires.  I imagine the queue gets created with a TTL of -1 and then something goes wrong to prevent the expiration being set correctly.

**Comment by fujifish** [comment]
Can you provide the whole key name as created by busmq?

**Comment by kpturner** [comment]
Difficult because they don't exist long enough for me to capture the info. I temporarily changed the ttl to 1000 so I could get time to capture it:
![image](https://cloud.githubusercontent.com/assets/308646/13881159/a775bde8-ed17-11e5-934d-45b2268e4b30.png)

**Comment by fujifish** [comment]
I'm confused. I thought the leaked key had an expiration of -1, why would you need to increase the ttl to 1000?

**Comment by kpturner** [comment]
Because at the moment it is not leaving any orphaned records on the database, so I don't have any examples to give you.  I can only give you an example that works just so you can see the key format.  They ones that do work are no different to the ones that don't - apart from the fact that the uuid part is unique.

**Comment by fujifish** [comment]
I've released version 1.3.3 that addresses a potentially rare possibility for the metadata key to get leaked. Perhaps it's the case you've been dealing with.
