### ISSUE TITLE
process out of memory

### ISSUE THREAD

**Issue by kpturner** [capriza/node-busmq#28]
I received the error below after leaving a process exchanging messages with busmq for a day or so.  I will see if I can spot a pattern.  I cannot yet confirm if the issue is caused by busmq or it is simply a victim of an issue elsewhere.

> <--- Last few GCs --->
> 
> 77761515 ms: Scavenge 697.2 (738.9) -> 697.2 (738.9) MB, 13.2 / 0 ms (+ 4.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
> 77763030 ms: Mark-sweep 697.2 (738.9) -> 697.2 (738.9) MB, 1515.0 / 0 ms (+ 6.0 ms in 2 steps since start of marking, biggest step 4.0 ms) [last resort gc].
> 77764634 ms: Mark-sweep 697.2 (738.9) -> 697.1 (738.9) MB, 1603.9 / 0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 2306CC95 <JS Object>
>     1: expire [C:\Users\kturner\repos\rns-node\node_modules\busmq\lib\connection.js:181] [pc=32A943DE] (this=2A7AE6BD <a Connection with map 0FDED031>)
>     2: arguments adaptor frame: 3->0
>     3: /* anonymous */(aka /* anonymous */) [C:\Users\kturner\repos\rns-node\node_modules\busmq\lib\queue.js:121] [pc=32AC4E7C] (this=230080DD <undefined>,key=33525105 <String[37]: bus:queue:out_default_rnsdta:meta...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by fujifish** [comment]
What version of busmq?

**Comment by kpturner** [comment]
Sorry - should have said that.   v1.3.3

**Comment by fujifish** [comment]
Any code that reproduces?

**Comment by kpturner** [comment]
Same code as sent on #21 but I am still trying to verify a pattern

**Comment by fujifish** [comment]
I've created a sample test case based on your sample code that captures heapdumps using [node-heapdump](https://github.com/bnoordhuis/node-heapdump): 
[busmq-sample.zip](https://github.com/capriza/node-busmq/files/187703/busmq-sample.zip)

According to the heapdumps, there is no memory leak.

Can you try to recreate the faulty scenario?

**Comment by kpturner** [comment]
Yes that is my intention - I just cannot promise a timescale at the moment because I have been rather overtaken by some higher priority things.   I cannot rule out issues with the windows version of redis.

**Comment by fujifish** [comment]
The stack trace shows the **node** process running out of memory, not redis.

**Comment by kpturner** [comment]
True - hadn't looked at it in detail I must admit.  So possibly busmq is a victim of some other leak.  I will look at it in more detail ASAP

**Comment by kpturner** [comment]
Here is some code that leaks in the way I am experiencing it.  Obviously there could be a glaring own goal in here showing that the leak is of my own doing - I really haven't had a chance to check it.  I don't expect you to do that either.  I will stick it here as an example and then try to narrow it down.  If you have time and spot it first then great.
[busmq#28.zip](https://github.com/capriza/node-busmq/files/188491/busmq.28.zip)

**Comment by fujifish** [comment]
One culprit I can see is that you continuously create a new `outq` object in method `_sendOnConnect` but never detach from it, so that queue probably gets leaked.

**Comment by kpturner** [comment]
But the outq is supposed to be permanent for as long as the application is running.  I don't want to create new one - I simply want to attach to one that already exists (or create it if it doesn't exist).  I don't ever want to detach from it because I don't want it to disappear until/unless the application stops running.   That said, perhaps it should not be a local variable?

**Comment by kpturner** [comment]
I made a small tweak.  It still leaks memory - but not at the same alarming rate:
[busmq#28.zip](https://github.com/capriza/node-busmq/files/189565/busmq.28.zip)

**Comment by kpturner** [comment]
This leaks about 127kb per hour

[busmq#28.zip](https://github.com/capriza/node-busmq/files/189703/busmq.28.zip)

**Comment by fujifish** [comment]
@kpturner do you have any updates? I want to close unless you can say for sure it;s a problem with busmq

**Comment by kpturner** [comment]
I will work on it today and close it afterwards once I have something definitive if that is ok.

**Comment by kpturner** [comment]
So I took your busmq_sample from above and tried it out and can confirm that it exhibits no signs of a leak.  However, it is not representative of the "use case" here.   In this case, the outbound queue (to the worker) must be a single consistent queue (and it is in your sample) but the queue on which the worker must respond must be a unique queue for every transaction.   In the real world example you have multiple clients and multiple workers.  The client sends the message and it may be picked up by any of the workers, but the worker must respond to the client (and only the client) that sent the message - with no possibility of a different client picking it up.  On a previous "issue" you suggested that the only way to do this was to generate create a unique response queue for each request. 

So I have taken your sample and modified it so that the queue receiving the response is based on the counter you created.  The creation of the inbound queue, and the events associated with it, take place in the "sendToWorker" function.

If you run this (I increased the counter to 20000) it leaks like a sieve.   I still do not know if the leak is directly related to busmq though - just that the "use case" exhibits a leak.   There may be a better way to do what I want to do here of course.....
[busmq_sample.zip](https://github.com/capriza/node-busmq/files/217184/busmq_sample.zip)

**Comment by kpturner** [comment]
Interestingly, if you use the exact same sample code, but change the code so that the inbound queue is not unique for each request, but is unique for the client, then it does not leak (at least not to any great extent).  In other words, change:
`var inq="inq_"+count.toString();`
to
`var inq="inq_"+process.pid;`

**Comment by fujifish** [comment]
I have a feeling it's related to how the code is structured. Take a look at this blog post: http://info.meteor.com/blog/an-interesting-kind-of-javascript-memory-leak

Try removing all listeners from the queue when you detach to release any long lasting references.

**Comment by kpturner** [comment]
Possibly so, but it is interesting that it only leaks when the queue changes its name on each sendToWorker.  What do you mean by "removing all listeners"?  Do you mean for each blah.on() perform a blah.off() or something else?

**Comment by kpturner** [comment]
I tried
`
appq.removeAllListeners();
appq.detach()
`
But the code still leaks memory at the same alarming rate

**Comment by kpturner** [comment]
I have done some further tests and simplified matters.
 
In this version of "sendToWorker" we do not have any listener for the "message" event

`function sendToWorker(workerq,count) { 
    var inq="inq_"+count.toString();
    var appq=bus.queue(inq);
    appq.on('attached',function(){
        appq.detach();
        appq=null;
        console.log('message ' + count); 
        if (count === 0) {
            console.log('All Done. duration: ' + (Date.now() - start));
            workerq.detach();   
            bus.disconnect();
            process.exit(0);
        }
        if (count % 2000 === 0) {
            heapdump.writeSnapshot(__dirname + '/heapdump/heapdump-' + Date.now() + '.heapsnapshot', function(err, filename) {
                sendToWorker(workerq,--count);
            });
        } else {
            sendToWorker(workerq,--count);
        }      
    })          
    appq.attach({ttl:1});  
    appq.consume(); 
}`

This still leaks memory at the same rate.

If you comment out this line:
`appq.consume(); `

it does not leak at all.

**Comment by fujifish** [comment]
If you comment out `consume` you stop getting messages and `sendToWorker` is not being called over and over again. That's why the leak goes away.
Anyway, please try version 1.5.2. When I run your code with that version I don't see a leak.

**Comment by kpturner** [comment]
I am not that stupid (although you can be forgiven for thinking as much :)  )
It does get called over and over again.  Look at the code - the sendToWorker is called in the "attached" event.   I simply moved everything that ran in the "message" event to the "attached" event.

So it leaks with the "consume" and not when it is commented out.

I will give 1.5.2 a try.....

**Comment by kpturner** [comment]
That's it!  1.5.2 fixes the leak :)

What changed?  Did you make a specific fix for a memory leak or has some code restructuring for other features inadvertently cured it?

**Comment by fujifish** [comment]
There were some major changes for supporting ioredis and some other stuff.
After running your test I found one last thing that caused a leak (not the same one you were experiencing) that was a result of a change I made a few days ago.
Ok to close this?

**Comment by fujifish** [comment]
BTW, sorry missing the not notcing sendToWorker did get called and I missed it. Too fast on the comments some times..

**Comment by kpturner** [comment]
No worries - thanks for the help
