### ISSUE TITLE
Federation server response

### ISSUE THREAD

**Issue by oritpersik** [capriza/node-busmq#29]
@all
What do i need to return from the  federation server to '/my/fed/path'  route ?
I catch the incoming request '/my/fed/path' (and send status 200) in my federation server from the second data center.

but when i want to federate a queue, I am not caught in the fed.on('ready') event.
Anyone can help ?

**Comment by fujifish** [comment]
If you provide some code I can point you in the right direction. You can also look at the federation tests in the tests folder

**Comment by fujifish** [comment]
Just noticed your question more closely, you don't need to handle the federation path yourself in the server, busmq does that for you. Just specify the path in the busmq creation options, and the federation server will automatically listen for connecting clients on that path.

```javascript
var http = require('http');
var httpServer = http.createServer(); // create the http server to serve as the federation server. you can also use express if you like...
httpServer.listen(8881);
var Bus = require('busmq');
var options = {
  redis: 'redis://127.0.0.1', // connect this bus to a local running redis
  federate: { // also open a federation server
    server: httpServer,  // use the provided http server as the federation server
    secret: 'mysecret',   // a secret key for authorizing clients
    path: '/my/fed/path' // the federation service is accessible on this path in the server
  }
};
var bus = Bus.create(options);
bus.on('online', function() {
  // the bus is now ready to receive federation requests
});
bus.connect();
```

**Comment by jokeyrhyme** [comment]
I have a working example of federation working here:
- https://github.com/blinkmobile/no-polling-example

As @fujifish suggests, I create the `http.Server` listener first, then I pass it to both Hapi.js (my static web service in this case) and to BusMQ. So I have both "normal" web traffic and BusMQ WebSocket traffic being served from the same port.
