### ISSUE TITLE
browser library uses TextDecoder: missing in IE, Safari, etc

### ISSUE THREAD

**Issue by jokeyrhyme** [capriza/node-busmq#32]
The busmq browser library uses `TextDecoder`:
- https://github.com/capriza/node-busmq/blob/master/browser/ws.js#L75

Unfortunately, it isn't available in Safari or IE:
- https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder#Browser_compatibility
- https://github.com/Fyrd/caniuse/issues/1195

The WebSockets feature _is_ available in these environments, however, so it might be worth finding an alternative to `TextDecoder` if broader browser / device compatibility is desired:
- http://caniuse.com/#feat=websockets

**Comment by fujifish** [comment]
For now, try using this: https://github.com/inexorabletash/text-encoding
If it works, I'll see if I can either include it or replace TextDecoder completely.

**Comment by jokeyrhyme** [comment]
Oh cool. Well, I don't like the idea of including required polyfills. That makes it difficult to produce optimised builds. But maybe mentioning it in the browser support part of the README.md would be sufficient.

I'll give this a try today and let you know how it goes. Is there there a specific message I should try to send to confirm that this is working?

**Comment by jokeyrhyme** [comment]
Yep, that library works for me. I can see expected output in Safari Technology Preview 2 which was otherwise broken.

I'm using browserify, and this is was I put in my entry point:

```js
import encoding from 'text-encoding';
global.TextEncoder = global.TextEncoder || encoding.TextEncoder;
global.TextDecoder = global.TextDecoder || encoding.TextDecoder;
```

As long as that runs before the BusMQ stuff, everything is terrific. Thanks!

**Comment by jokeyrhyme** [comment]
In case anyone else is having issues, this is how I load the polyfill in using webpack:

```js
webpackConfig.plugins = [
  new webpack.ProvidePlugin({
    TextDecoder: 'imports?this=>global!exports?module.exports.TextDecoder!text-encoding'
  })
];
```

There's probably a cleaner way, but I tried a few different versions of the above and this is what worked for me. :)

**Comment by noscript** [comment]
Google brought me here. So in case anyone else is *still* having an issue:
```js
webpackConfig.plugins = [
    new webpack.ProvidePlugin({
        TextDecoder: ['text-encoding', 'TextDecoder']
    })
];
```

**Comment by hjmccain** [comment]
well, this is helpful!

![screen shot 2018-03-26 at 10 30 02 am](https://user-images.githubusercontent.com/18276108/37912525-b500fbc6-30e0-11e8-868c-2c8c832cf89b.png)
