### ISSUE TITLE
Using busmq with a redis cluster

### ISSUE THREAD

**Issue by kpturner** [capriza/node-busmq#35]
If I set up a genuine redis cluster as described here: http://redis.io/topics/cluster-tutorial how do I then configure busmq to utilise the cluster?  Is it simply a case of passing the is redis masters in the array that the connect()method accepts and off we go, or is there more to it than that?

**Comment by kpturner** [comment]
I think I can answer my own question - I specify ioredis as the driver, correct?

**Comment by fujifish** [comment]
Yep, that's correct. You can also take a look at the tests to see more details.

**Comment by kpturner** [comment]
OK thanks
