### ISSUE TITLE
Minor memory leak - version 1.5.4

### ISSUE THREAD

**Issue by kpturner** [capriza/node-busmq#39]
I have noticed another memory leak in my app - about 1kb per 30 seconds.

Example attached
[busmq.zip](https://github.com/capriza/node-busmq/files/287276/busmq.zip)

**Comment by fujifish** [comment]
The only things I see getting leaked are _system_ related stuff. Not sure how they relate to busmq but
I'll keep invetigating.

**Comment by kpturner** [comment]
OK - out of interest what do you mean by "system related" and how can one tell?

**Comment by fujifish** [comment]
By looking at the heapumps through chrome DevTools. Comparing dumps chrome reveals the leaks items. In this case the items appear to be "arrays" with mainly "code reallocation", "compiled code" and "system" items.
It doesn't mean that the origin isn't busmq though ...

**Comment by fujifish** [comment]
I've done some more testing. I've put the worker in the same file as the app and disabled heapdump. 
I've changed the app to push a message every 10 milliseconds to increase the stress and let it run for several minutes, examining the memory during the entire run.
Result is that memory slowly increases, then sharply decreases, repeatedly. This happens due to the GC kicking in, but overall, over time I did not see a memory leak.

Here is the code I used to test. Can you give it a try and let me know if you see anything different?

```javascript
var Bus = require('busmq');
var path = require("path");
// var heapdump=require("heapdump");
var id=0;

// var w = require("child_process").fork("worker");

// Heap dump
// setInterval(function(){
//     var hd=path.join(__dirname,"heapdump",Date.now().toString()+".heapsnapshot");        
//     heapdump.writeSnapshot(hd,function(err, filename) {
//         // console.log('Dump written to', filename);
//     });
// },10000) 

var bus = Bus.create({redis: ['redis://127.0.0.1:6379']});

var q = bus.queue('foo');

setInterval(function(){
    q.push({
        outq:   'bar',
        id:     id++
    });
},10)


bus.on('online', function() {
  
  
  var i = bus.queue('bar');
  q.on('attached', function() {
    console.log('attached to queue');
  });
  
  i.on('message',function(response, id){
      // console.log(response)
  })
  
  i.on('attached',function(){
    q.attach();               
  })
  
  i.attach();
  i.consume();
  
});


bus.connect();

(function() {
  var Bus = require("busmq");
  var bus = null;

  console.log("worker is alive")

  var bus = Bus.create({redis: ['redis://127.0.0.1:6379']});
  bus.on('error', function(err) {
    // an error has occurred
    console.log(err);
  });
  bus.on('online', function() {    
      
      var inq=bus.queue("foo");
      inq.on("attached",function(){
          console.log("worker attached")    
      })
      inq.on("message",function(message,id){
          //console.log(message)
          var msg=JSON.parse(message);
          var outq=msg.outq;
          var outq=bus.queue(outq);
          // console.log("Worker got "+msg.id)
          function onattached(){
              outq.push(msg.id);
              outq.removeListener("attached",onattached);
              outq.detach();
              outq=null;
              msg = null;
          }
          outq.on("attached",onattached)
          outq.attach();
          //outq.consume();
      })
      inq.attach();
      inq.consume();  
  });
  bus.on('offline', function() {
    // the bus is offline - redis is down...
  });

  // connect the redis instances
  bus.connect();
})()
```

**Comment by kpturner** [comment]
Looking purely at the memory usage it does seem to stay steady (even with the heapdump activated) when you monitor the process.  However, the heapdumps still get bigger.  So are we saying that heapdumps are not a good way to detect memory leaks?

**Comment by fujifish** [comment]
I hope this is resolved for you now. If not, please reopen with additional information.
