### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by tlenex** [capriza/node-busmq#41]
From time to time, I'm experiencing this issue:

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write after end
>     at writeAfterEnd (_stream_writable.js:159:12)
>     at Socket.Writable.write (_stream_writable.js:204:5)
>     at Socket.write (net.js:618:40)
>     at Sender.frameAndSend (/home/user/dist/node_modules/ws/lib/Sender.js:224:22)
>     at /home/user/dist/node_modules/ws/lib/Sender.js:126:12
>     at /home/user/dist/node_modules/ws/lib/PerMessageDeflate.js:271:5
>     at afterWrite (_stream_writable.js:346:3)
>     at onwrite (_stream_writable.js:337:7)
>     at WritableState.onwrite (_stream_writable.js:89:5)
>     at afterTransform (_stream_transform.js:79:5)

Seems like it's in `ws` module.

**Comment by fujifish** [comment]
should be fixed in version 1.5.6.

**Comment by fujifish** [comment]
released version 1.5.7 with the additional fix

**Comment by tlenex** [comment]
thank you! :)
