### ISSUE TITLE
Odd Messages

### ISSUE THREAD

**Issue by coreyperkins** [capriza/node-busmq#44]
I've been tinkering with busmq, but just very, very briefly. I did notice something unexpected when running the sample code. There are some entries in redis where the key and value are numerical entries that I did not do a "push" for. I suspect this might have something to do with message ordering, but I wanted to pitch it out there for feedback and to make sure something wasn't a miss in 1.6.2.

Thanks!

Corey
<img width="801" alt="screen shot 2016-11-16 at 11 50 57 pm" src="https://cloud.githubusercontent.com/assets/429696/20377877/1c982282-ac58-11e6-8eab-fe0c12536baf.png">

**Comment by fujifish** [comment]
These numbers are the IDs of the messages. It's done this way to avoid performing string manipulation on messages in the lua scripts that push and pop from the queue.
