### ISSUE TITLE
Missing "}" on documentation first example

### ISSUE THREAD

**Issue by pinazo** [capriza/node-busmq#45]
A tiny typo, all lines of bus instantiation are missing "}" before last ")". 

Example:

`var bus = Bus.create({redis: ['redis://192.168.0.1:6379', 'redis://authpass@192.168.0.2:6379']);`

should be

`var bus = Bus.create({redis: ['redis://192.168.0.1:6379', 'redis://authpass@192.168.0.2:6379']});`

**Comment by fujifish** [comment]
Fixed. Thanks!
