### ISSUE TITLE
Duplicate Messages

### ISSUE THREAD

**Issue by JoshEH81** [capriza/node-busmq#47]
I have a pair of scripts setup with identical code, but sending to differently named queues, both are listening to a pubsub channel for incoming messages. They take the messages coming from the pubsub channel and push them to reliable delivery queues so they can be acted on. The problem is queue A is getting 12 copies of the message while queue B has just the one instance of the message. I've cleared redis of all the keys are started the scripts fresh but the same issue keeps happening and the push callback function only reports a single submission of the message.

Code:

	var config = require('./_siteconfig.js');

	var Bus = require('busmq');

	var pupsubBus = Bus.create({redis: ['redis://'+config.redisInfo.hostname+':'+config.redisInfo.port]});
	var s;

	var queueBus = Bus.create({redis: ['redis://'+config.redisInfo.hostname+':'+config.redisInfo.port]});
	var q;

	// Incoming Pub/Sub
	pupsubBus.on('online', function() {
		console.log('pupsubBus online');

		s = pupsubBus.pubsub('inbound');

		s.on('message', function(message) {
			console.log("Got Message: "+message);
			try {
				q.push(message, function(err, id) {
					console.log('err: '+err);
					console.log('id:'+id);
				});
			} catch(e) {

			}
		});

		s.subscribe();
	});

	pupsubBus.on('error', function(err) {
		console.log('pupsubBus Error: '.err);
	});

	pupsubBus.on('offline', function() {
		console.log('pupsubBus Error: Offline');
	});

	pupsubBus.connect();

	// Outoing Queue
	queueBus.on('online', function() {
		console.log('queueBus bus online');

		q = queueBus.queue('outboundA');

		q.on('attached', function() {
			console.log('queueBus attached to queue');
		});

		q.attach();
	});

	queueBus.on('error', function(err) {
		console.log('queueBus Error: '.err);
	});

	queueBus.on('offline', function() {
		console.log('queueBus Error: Offline');
	});

	queueBus.connect();

**Comment by fujifish** [comment]
Can you please provide a complete test script that reproduces this? should much easier for to check it

**Comment by JoshEH81** [comment]
My apologizes, while attempting to make a set of test scripts for you I stumbled on an unexpected old docker container with scripts that were listening to the same channel and sending the duplicate messages.
