### ISSUE TITLE
Remove hiredis from dependencies

### ISSUE THREAD

**Issue by avaly** [capriza/node-busmq#49]
I could not find any code using `hiredis`, even though is required in `package.json` as a dependency.

**Comment by fujifish** [comment]
the node_redis and ioredis versions currently used by busmq use hiredis as the default parser if it is installed. The newer versions do not need it any more. 

I'll see if I can update node_redis and ioredis to the latest versions.

**Comment by fujifish** [comment]
I removed the dependency on hiredis - its not really needed.
Released version 2.1.0 with the fix
