### ISSUE TITLE
Move `redis` and `ioredis` to peerDependecies

### ISSUE THREAD

**Issue by avaly** [capriza/node-busmq#50]
There's no point on depending on both modules if only one will be used. Let the consumer of this module decide which driver they want to use and advise to install the appropriate driver in their application's dependencies.

**Comment by fujifish** [comment]
May I ask why it is a problem to install both? 
I find it would be easier for users of busmq to not worry about it

**Comment by avaly** [comment]
The use case I'm running into now is using `busmq` in a project built with docker. Starting from the docker base image `node:6-slim`, Python is not installed there, which is needed for `node-gyp`, which is needed to build `hiredis` (which is not even used BTW, at least not that I could find in the repo).

**Comment by avaly** [comment]
If you feel `peerDependencies` is not ideal, at least consider moving them to `optionalDependencies`, so it does not block the install of this module in an environment where `node-gyp` is not available.

**Comment by fujifish** [comment]
Does the fix for #49 also solve this problem?

**Comment by avaly** [comment]
Sure, version `2.1.0` solves my immediate blocker. Thanks!

However I still think you should consider moving the two remaining redis libraries to `peerDependencies`.

Feel free to close this issue otherwise.
