### ISSUE TITLE
Please bump "websocket-stream" to  3.0.0 or above

### ISSUE THREAD

**Issue by shenghu** [capriza/node-busmq#53]
Now busmq uses "websocket-stream@2.0.2" which uses ws@0.8.1. ws@0.8.1 has a security Vulnerability, see https://nodesecurity.io/advisories/67. 

Can you please bump websocket-stream to 3.0.0 or above? This is pretty urgent.

**Comment by fujifish** [comment]
I tried updating to  v3.3.3 but it seems to break busmq federation.
It might take a while to find the cause. 
If it's urgent, perhaps you would be willing to investigate

**Comment by fujifish** [comment]
Found the cause, will be releasing a new version shortly

**Comment by fujifish** [comment]
Actually, busmq uses ws@1.1.0 directly, not relying on the ws usage embedded in websocket-stream, so there doesn't seem to be a problem here.
Released version 2.2.0 in any case.

**Comment by shenghu** [comment]
@fujifish thanks for quick fix!
