### ISSUE TITLE
Remove 'ws@1.1.0' from optionalDependencies

### ISSUE THREAD

**Issue by shenghu** [capriza/node-busmq#54]
Is it possbile to remvoe it as ws@1.1.0 has security vulnaribility.  

```
 "optionalDependencies": {
    "ws": "1.1.0",
```

**Comment by fujifish** [comment]
Are you asking to upgrade to a newer version or completely remove it?
If you don't need federation, you can install busmq it without optional dependencies (--no-optional)

**Comment by shenghu** [comment]
@fujifish if it can not be removed, it is better to be upgraded. :)

**Comment by fujifish** [comment]
Upgraded ws to 1.1.5

**Comment by shenghu** [comment]
@fujifish Thanks!
