### ISSUE TITLE
Request/Response message pattern?

### ISSUE THREAD

**Issue by james7272** [capriza/node-busmq#55]
I am evaluating busmq for a project and so far it meets the needs very well. But I cannot see how to implement a request/response feature.

Is there a way for the consumer of a message from either a queue or a pub/sub to respond directly to the sender without needing to setup a channel? This is a very common requirement for services like databases, authentication etc.

**Comment by fujifish** [comment]
There currently isn't any built-in mechanism for that, and I agree it's very useful for a microservices setup.

It should be very easy to implement:
1. a service implementor creates a public Service Queue (as consumer) for receiving requests
2. a requestor creates a private Response Queue for receiving responses (as consumer)
3. requestor sends a request to the service implementor via the Service Queue. every request contains the private Response Queue name of the requestor
4. upon completion, the service sends a response to the requestor via the private Response Queue that was specified on the request.

I sounds like a lot, but it's quite simple actually. I was thinking of implementing this pattern a while back but haven't got around to it.

**Comment by james7272** [comment]
Thanks, that sounds feasible enough. I can add it to the abstraction layer I have.

**Comment by fujifish** [comment]
If it's still relevant, I've released version 2.3.0 that includes a new "Service" object that implements the request/response pattern, specifically for helping in the implementation of a microservices architecture.
Details here: https://capriza.github.io/node-busmq/usage/#service
