### ISSUE TITLE
Service disconnect event does not follow documentation

### ISSUE THREAD

**Issue by Wildenhaus** [capriza/node-busmq#58]
In the documentation, it states that[ a service emits the "disconnected" event](https://capriza.github.io/node-busmq/usage/#service-events). This [differs from the implementation](https://github.com/capriza/node-busmq/blob/b654131d00677b7a17bb254d1d43b6846248aec9/lib/service.js#L50), which emits "disconnect".

**Comment by fujifish** [comment]
Fixed documentation. 
Thank you!
