### ISSUE TITLE
What can i  use for monitoring

### ISSUE THREAD

**Issue by insanehong** [capriza/node-busmq#64]
Hi. 

What can i  use for monitoring with ui?

**Comment by fujifish** [comment]
We use readily available redis monitoring tools for monitoring CPU, memory, commands, network, etc. Specifically, we rely on AWS ElastiCache for that has built-in monitoring.
Does that provide what you're looking for?

**Comment by insanehong** [comment]
@fujifish I looking for queue monitoring like a https://github.com/bee-queue/arena/issues t

**Comment by fujifish** [comment]
Unfortunately I'm not aware of any dashboard available for busmq similar to bee-queue/arena.

**Comment by insanehong** [comment]
Well noted with thank you
